# Generated by Django 2.2.6 on 2019-12-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_defense_day', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('industry', 'Industry'), ('supervisor', 'Supervisor'), ('referee', 'Referee'), ('admin', 'Admin')], default='student', max_length=11, null=True),
        ),
    ]
