# Generated by Django 2.2.6 on 2020-01-04 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui_defense_day', '0002_auto_20200104_2025'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'presenter')},
        ),
    ]
