# Generated by Django 2.2.6 on 2019-12-31 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ui_defense_day.models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_defense_day', '0002_user_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Industry',
            },
            bases=('ui_defense_day.user',),
            managers=[
                ('objects', ui_defense_day.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('industry', 'Industry'), ('referee', 'Referee'), ('admin', 'Admin')], default='student', max_length=11, null=True),
        ),
    ]
