# Generated by Django 2.2 on 2019-12-26 11:08

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_defense_day', '0002_auto_20191226_0853'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleCoefficent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('presenter', 'Presenter'), ('industry', 'Industry'), ('supervisor', 'Supervisor'), ('referee', 'Referee')], max_length=20)),
                ('coefficent', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Presenter',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SupervisorOfPresenter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('ui_defense_day.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
