# Generated by Django 2.2 on 2019-12-26 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui_defense_day', '0002_auto_20191226_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenter',
            name='presenter',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PresenterUSer', to=settings.AUTH_USER_MODEL),
        ),
    ]
