# Generated by Django 2.2.6 on 2020-01-05 04:35

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_defense_day', '0003_auto_20200104_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', django_jalali.db.models.jDateTimeField(verbose_name='تازیخ شروع')),
                ('end_date', django_jalali.db.models.jDateTimeField(verbose_name='تاریخ پایان')),
            ],
        ),
    ]
