# Generated by Django 2.2.6 on 2020-01-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_defense_day', '0007_auto_20200105_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(auto_now=True),
        ),
    ]
