# Generated by Django 2.2.6 on 2020-01-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui_defense_day', '0008_event_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rolecoefficent',
            name='job',
            field=models.CharField(choices=[('student', 'Student'), ('industry', 'Industry'), ('supervisor', 'Supervisor'), ('referee', 'Referee')], max_length=20, unique=True),
        ),
    ]
